counters_data = {
    "ana": "**Ana**\n\nOf course, the classic counter is just to run Kiriko 4head and Suzu her anti-nade, but I want to look at situations where you would not want to run Ana, and that is what you are running. A brawl comp, where you would either be running Baptiste or in a full-on poke matchup, where Baptiste just does more damage. So, team comp wise, that is where you can get an advantage, individually speaking. Diving or pressuring the Ana, of course, is a good move, either running straight into the back line as Reinhardt, Ramattra, or just diving in on any hero. ",
    "ashe": "**Ashe**\n\nAshes strengths lie in her range and damage, but falter in her sustain and mobility. Duelist heroes like Genji and Tracer and to a lesser extent, Sombra can easily demolish her, especially without a mercy pocket and especially on maps with high ground. You really ought to be playing Winston, Ball or D.va. You lose against Ashe once she has all the space in the world, specifically on high ground-based maps. So, you need to play heroes that can contest that. Kiriko and Moira are even solid picks, as long as you can pull off the flanking playstyle.",
    "baptiste": "**Baptiste**\n\nBap's kind of the jack of all trade support hero. He's tough to nail down a specific hard counter for, because there kind of isn't one. I suppose if you are on DPS, playing them well is just probably your best bet, and that sounds kind of vague, but what I mean is choosing and picking a specific playstyle. For example, flanking on Junkrat to get that one shot off, or flanking on Reaper instead of frontlining, or just taking good, well-timed angles on Ashe or Sojourn things like that can catch a Baptiste out in the open. And as for the other tank and support matchups, most of them are pretty neutral, if not similar to Ana.",
    "bastion": "**Bastion**\n\nThe noob stomper of a pick. Honestly, any hitscan pick, and even Sojourn, who can easily farm rail off him, can melt Bastion's mega hitbox. I will say that the counter to Bastion is more of a playstyle thing rather than hero specific. As long as you can play defensive during Bastion’s turret cycles, you are pretty much good to go. Any hero can pretty much kill Bastion if he hasn't got turret form. ",
    "brigitte": "**Brigitte**\n\nBrigitte thrives the best against dive comps, where Brig falters is in the ranged matchups against snipers or mercy-based comps, or in straight up brawl comps, like your Lucio Bap and Rein stuff on Lijiang. Despite Brick being a melee hero, she wants to keep a relatively far distance away from the enemy tank, but she also wants to get close eventually in the midfight to get those swings off. Those two types of compositions can make either of those goals really tough for Brick to achieve.",
    "cassidy": "**Cassidy**\n\nCassidy is a pretty versatile hero, more of a jack of all trades, master of none kind of thing. So, you can either outrange him with heroes like Ashe, Mercy, Zen Widow, and Hanzo, or you can abuse his lackluster mobility with a dive or duelist-oriented comp. He has not really got too much of a glaring weakness, and most of his so-called counters are soft counters.",
    "d.va": "**D.va**\n\nIf the D.va is not competent or loves stacking main, then the solution is easy. Go Zarya and hold M1, or just go high damage heroes to obliterate the D.va (e.g., Bastion, Symmetra, Sojourn, Soldier). But if you are going against a good D.va who does not feed and correctly marks high grounds, then it is a bit more complicated and a bit more team oriented. If you can split the D.va’s attention, that is what can cause great panic. Make her choose between marking and controlling high grounds and peeling her backline. Sombra is also a good hero against her considering the hack and range advantage she has.",
    "doomfist": "**Doomfist**\n\nGenerally speaking, there is a few things you can do. Either run heroes with hard CC like Orisa, Ana or Sombra, or run heroes that can deny Doomfist any space, like D.va, Sombra, Tracer, Echo, and even Zen with his orbs.",
    "echo": "**Echo**\n\nSimilar to Pharah, as you will see later range, can often be a big issue for Echo. Two Cassidy shots one Hanzo arrow, and Echo automatically has to play way more passive. If she lands her stickies and beam combo up close, you are likely going to die to her. Most of the tanks do not interact with Echo barring D.va, but it's also pretty easy to feed on D.va against an Echo. I will say that Sombra is also a decent counter, since the hack from Invis paired alongside Echo’s big hitbox can easily melt Echo on the ground.",
    "genji": "**Genji**\n\nMoira, and Brigitte can be tough to deal with alongside a high charge Zarya. Sustain and bulky brawl comps do not really bode well for Genji, since heroes like Reinhardt, Mei, Baptiste, and Lucio can easily tank through your dash and your shuriken most of the time.",
    "hanzo": "**Hanzo**\nI have always seen Hanzo like an alternative Cassidy with higher burst damage in exchange for lower sustain. Heroes like Genji, Doomfist, Sombra, and Tracer should easily be able to squash the Hanzo with no issue. Sigma, I think, is also an underrated tank to play against because you can mark any angles he takes.", 
    "illari": "**Illari**\n\n[REDACTED]",
    "junker queen": "**Junker Queen**\n\nJunker Queen's two biggest weaknesses, even from release, has always been her range and mobility. Running heroes like Sigma Pharah, Ashe, Hanzo, Zen, Mercy and others can keep Junker Queen at bay from range, and because of her limited mobility, she should have a tough time getting up close. Ana and Kiriko can also deny value from her adrenaline surge and her ultimate, respectively. Playing Ramattra or Zarya are also decent choices as long as you force commanding shout early before you close the distance.",
    "junkrat": "**Junkrat**\n\nThe classic counter is Pharmercy, of course, but Junkrat's kind of built like a glass cannon. Zarya can absorb his bombs and melt him down. D.va can eat all kinds of spam from him, and most importantly, most heroes honestly have a relatively decent matchup against him as long as you're aware of where he is. A Junkrat sneaking up on you for a mine concussion combo is a recipe for disaster. Maybe even going Hanzo and scouting out his flanks could be worthwhile. ",
    "kiriko": "**Kiriko**\n\nI genuinely think this hero does not have a hard counter. She is only really bad in situations where you wouldn't pick Kiriko anyways, like on Circle Royale, where you should be playing Bap, Zen, but even then, you could get away with Kiriko in your rank games, I suppose. Pouncing on Kiriko if she is isolated when you are playing as a flanker or just being more aware of your surroundings as a sniper in case a Kiriko tries to pounce on you are all precautionary measures that you can take. ",
    "lifeweaver": "**Lifeweaver**\n\n[REDACTED]",
    "lucio": "**Lucio**\n\nAny CC can stop his reddit antics. And if he is supporting a DPS on a flank, someone like a Brig can do that job better. For example, a Sojourn. Lucio should lose against a Brig Sojourn. But as for direct counters, there is not really too much to say. Honestly, most of his matchups are pretty neutral.",
    "mei": "**Mei**\n\nIf you play very split against Mei and you also play to out range her, then the value she can get from the wall will be at most, quite limited. Heroes with high sustain like Ramattra and Orisa can also withstand getting split from Mei's wall. ",
    "mercy": "**Mercy**\n\nMercy has some pretty rudimentary counters, thriving on ranged maps, but struggling up close due to her low sustain. Get behind her on any flank in the game, or close the distance with broader compositions. The Brig vs. Mercy matchup is interesting, since if you can close the distance from Brig, Mercy is kind of screwed.",
    "moira": "**Moira**\n\nMoira is probably the best support duelist in the game, thanks to her insane sustain. However, she has no utility. Ana nades really pose a threat to her, and while she has not got any direct or individual counters, she's a utility burden on her team. Things like immortality, field Suzu, Nade sleep, and Zen orbs, if used correctly, will often naturally outvalue what Moira can do. If you are struggling individually, I recommend going heroes with high sustain. Moira is simply not outdueling you if you are on Brig.",
    "orisa": "**Orisa**\n\nSimple, either run Zarya and or focus stuff around the Orisa. Even on Zarya, you are still trying to prioritize squishy heroes where you can. If you are shooting at Orisa in Fortify whilst there are squishies that you could be shooting, then there is a problem. Abuse the fact that Orisa has limited mobility and utility by fighting for the key spaces of the map around the Orisa.",
    "pharah": "**Pharah**\n\nOf course, the average gold player is getting yelled “play hitscan Lmao”, but it is a bit more nuanced than that. The biggest thing is that if you are going to play Hitscans like Soldier, Widow Cassidy, you really need to keep the range. Pharah loves duels in close range, especially getting up close with that concussive blast. So, if you are running something like an Ana, Zen and Widowmaker, you really cannot let the Pharah get on top of you. In terms of projectile counters, Echo is also really, really good against Pharmercy and for tanks go D.va, of course. ",
    "ramattra": "**Ramattra**\n\nSimilar to Orisa, I think it's kind of futile trying to run up against the Ramattra. Wrecking Ball in particular, I found very annoying to play against as Ramattra because you do not have any hard CC to deal with him. And if the enemy team are running an Ana Zenyatta combo, then those two heroes can prevent Ramattra from closing the distance.",
    "reaper": "**Reaper**\n\nBefore I get into his counters, I want to briefly cover his two playstyles. Reaper either frontlines against squishy tanks, or he flanks against a glass cannon immobile squishies. So, to counter him, make either or both of those playstyles hard to pull off. Orisa, Torb, Cassidy, Brig, and Ana are probably the hardest counters to Reaper in the game. Or, if you are on a more open map, Pharah and Echo can work too, as well as other ranged options. ",
    "reinhardt": "**Reinhardt**\n\nThere is a bunch of things you can do against Reinhardt. Ramattra pretty much melts him. He cannot do much on maps with high ground, so running ranged threats like Ashe and Mercy are a pain to deal with. And also, playing against Ana-Zen is absolutely hellish. Due to Nade sleep and discord. In short, if you are going to play in close range against Reinhardt, make sure you soften him up beforehand (Poke his shield/armor). A Rein with limited shield cannot do much against a dive or rush if he hasn’t got earthshatter.",
    "roadhog": "**Roadhog**\n\nHonestly, every hero in this game counters Hog. Just play the game and counter him by proxy. Orisa Ana, Zen, and a good Tracer are particularly annoying for him to play against. If you’ve got a feeding DPS, playing Lifeweaver can also save them from getting killed by the hook.",
    "sigma": "**Sigma**\n\nSigma, of course, loves to keep his range, but he does have the tools to defend himself if he gets walked upon. A good Reinhardt, for example, with good shield management or a good Junker Queen, or Zarya should be able to bully the Sigma up close. Symmetra, Junkrat, and to a lesser extent, Reaper can also kind of do the same thing. And because we are all about closing the distance, Lucio can help with that too. Ensure he cannot continuously poke your team uninterrupted, as that is where he excels.",
    "sojourn": "**Sojourn**\n\nBefore Sojourn had a pretty strict counter in Cassidy, since if Sojourn ever got close or power steered aggressively, Cassidy could just two shot the Sojourn. Now, that is less of a counter, but still a viable option. Playing tanks with slender hitboxes like Junker Queen and ensuring that it is tough for her to charge her rail gun off can lower how effective she is. Weirdly enough, I think Brig is also a decent pick against her, since she kind of acts like an aggression check if the Sojourn power slides aggressively. ",
    "soldier 76": "**Soldier: 76**\n\nHis biggest counter is any dive in the game. Even Lucio's can reliably win duels against a Soldier. Soldier just does not have any big, reliable bursts of damage, unlike Cassidy with the homing grenade, Sojourn with a railgun, or even Hanzo with the storm arrows. Sure, he has helix rockets, but that is tough to hit on a moving target. Take advantage of how squishy he can be and pounce when the opportunity shows itself. ",
    "sombra": "**Sombra**\n\nSombra's USP or unique selling points is her range. She's the flanker in the game with the most range. For example, she can farm a tank more easily than someone like a tracer, so just outrange the Sombra. One Hanzo arrow, two Cassidy body shots, one Widow body shot, and that Sombra is forced to use her translocator. You can also out-sustain the Sombra by running things like Torb and Brig, but be careful that you may not have enough mobility to directly contest her.",
    "symmetra": "**Symmetra**\n\nSymmetra thrives when she can get her level three beam up, melting down the enemy tank. Her alternative playstyle is a less resource intensive one, involving ticking off angles and spamming from range. Forcing Symmetra into that latter playstyle will make things tougher for her, since she is not microwaving your team.",
    "torbjorn": "**Torbjörn**\n\nOne of the classic counters against traditional dive heroes, Torb struggles at dishing out reliable damage from mid to long range, which is why heroes like Cassidy, Sigma, and Echo can quite easily burn him down on longer range maps. Just run snipers against him alongside Bap Zen to burn his turret, and you should be fine.",
    "tracer": "**Tracer**\n\nTracer is such a strong and versatile hero and there are not many direct counters to her. There's Torbjorn, of course, with his turret, but other people can destroy the turret anyways. Personally, I think the best counter to Tracer is to mirror her with support. A Tracer with Zen orbs or a Tracer with Brig packs will win against a regular Tracer. Brig in particular, also has that sustain too, so picking her is definitely a top solution.",
    "widowmaker": "**Widowmaker**\n\nHigh range, low mobility. Any dive tank, Genji, Tracer, Lucio, Kiriko, even Moira are all solid duelists to flush out the Widowmaker and eliminate her range advantage. Poke-brawl tanks like Ramattra and Reinhardt do not often interact with the Widow anyways, so their matchups are mostly neutral.",
    "winston": "**Winston**\n\nOf course, all the gold players will say that Reaper or even Bastion is a good counter. But if the Winston knows what he is doing and can get on top of the enemy squishies unless Reaper or Bastion sits in the backline, they are not going to be doing much. Now, they obviously are not bad picks, but they are just one small piece to the larger idea of running mad sustain. Winston is going to be doing fuck all against a Junker Queen, Brig, Ana, Torb, Cassidy or Reaper comp. Now, that Comp does have its own downsides, and it can be counted itself, but if you are really struggling against a Winston, look to get higher damage or higher sustain.",
    "wrecking ball": "**Wrecking Ball**\n\nSombra is the obvious counter here, just hacking from invisibility whenever he flanks. But other heroes like Tracer or Zen can deny the space he has before he dives. And similar to the Doom counters, heroes like Torb, Ana and D.va can actually absorb the dive itself. Choose your pick or choose both. ",
    "zarya": "**Zarya**\n\nZarya's two biggest weaknesses are her lack of sustain and her lack of mobility. Reinhardt Junker Queen and Ramattra can easily W key on her. Alternatively, heroes like Winston can cleave multiple enemies around the Zarya, especially if she is on low charge, either pummel the Zarya from high ground and from range, so that even if she is on high charge, she is built like a glass cannon and cannot last for long.",
    "zenyatta": "**Zenyatta**\n\nThe definitive glass cannon of Overwatch. If you can close the distance on a rush comp, Zen is kind of finished. Part of it is map dependent, but any hero who is competent at dueling and has mobility can give Zen a hard time. There is your classic Tracer, Sombra stuff. But heroes like Lucio Kiriko and Moira, and to a lesser extent, Baptiste, are supporters who can give Zen a tough time if they are playing aggressively in a flanker or DPS oriented style."
}

TankList = ["Dva", "Doomfist", "Junker Queen", "Orisa", "Ramattra", "Reinhardt", "Roadhog", "Sigma", "Winston", "Wrecking Ball", "Zarya"]
DPSList = ["Ashe", "Bastion", "Cassidy", "Echo", "Genji", "Hanzo", "Junkrat", "Mei", "Pharah", "Reaper", "Soldier 76", "Sombra", "Sojourn", "Symmetra", "Torbjörn", "Tracer", "Widowmaker"]
SuppList = ["Ana", "Baptiste", "Brigitte", "Illari", "Kiriko", "Lifeweaver", "Lucio", "Mercy", "Moira", "Zenyatta"]

herolist = [TankList, DPSList, SuppList]